export const GET_MEMBERS = "GET_MEMBERS";
export const MEMBERS_LOADING = "MEMBERS_LOADING";
export const MEMBER_CREATING = "MEMBER_CREATING";
export const MEMBER_DELETING = "MEMBER_DELETING";
export const USERS_SEARCHING = "USERS_SEARCHING";
export const SEARCH_USERS = "SEARCH_USERS";
