export const GET_COURSE = "GET_COURSE";
export const COURSE_LOADING = "COURSE_LOADING";
export const COURSE_UPDATING = "COURSE_UPDATING";
export const COURSE_DELETING = "COURSE_DELETING";
export const SET_COURSE = "SET_COURSE";
