export const GET_QUESTIONS = "GET_QUESTIONS";
export const QUESTIONS_LOADING = "QUESTIONS_LOADING";
export const GET_QUESTION = "GET_QUESTION";
export const QUESTION_LOADING = "QUESTION_LOADING";
export const QUESTION_CREATING = "QUESTION_CREATING";
export const QUESTION_UPDATING = "QUESTION_UPDATING";
export const QUESTION_DELETING = "QUESTION_DELETING";

export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const SET_PAGE = "SET_PAGE";
